<?php

namespace ContainerLGNNtud;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEquipment2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sKD5.Gs.App\Entity\Equipment' shared service.
     *
     * @return \App\Entity\Equipment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sKD5.Gs": it references class "App\\Entity\\Equipment" but no such service exists.');
    }
}
