<?php

<<<<<<< HEAD:var/cache/dev/ContainerZLMyazr/get_ServiceLocator_JIxfAsiService.php
<<<<<<< HEAD:var/cache/dev/ContainerFFfIZfl/get_ServiceLocator_JIxfAsiService.php
namespace ContainerFFfIZfl;

=======
namespace ContainerZLMyazr;
>>>>>>> 9b03bdf0df8650d60f8b2bd0d2214076809a92cf:var/cache/dev/ContainerZLMyazr/get_ServiceLocator_JIxfAsiService.php
=======
namespace ContainerBDdVKy1;
>>>>>>> 021acb7f1c1b8268aafe571d0af6e812e6d8d48c:var/cache/dev/ContainerBDdVKy1/get_ServiceLocator_JIxfAsiService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JIxfAsiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jIxfAsi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jIxfAsi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'twig' => ['privates', 'twig', 'getTwigService', true],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'twig' => '?',
        ]);
    }
}
