<?php

namespace ContainerZW1UA5M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SZ1vsQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S_z1vsQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S_z1vsQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EquipmentController::assign' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Controller\\EquipmentController::edit' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Controller\\EquipmentController::filterByCategory' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\EquipmentController::filterByUser' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\EquipmentController::show' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Controller\\EquipmentController::unAssign' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Controller\\MoviesController::edit' => ['privates', '.service_locator.I4k6Jea', 'get_ServiceLocator_I4k6JeaService', true],
            'App\\Controller\\MoviesController::show' => ['privates', '.service_locator.I4k6Jea', 'get_ServiceLocator_I4k6JeaService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController::getUserEquipment' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Service\\EquipmentService::assignEquipment' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Service\\EquipmentService::editEquipment' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Service\\EquipmentService::getEquipmentOfUserPaginate' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Service\\EquipmentService::unAssignEquipment' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\EquipmentController:assign' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Controller\\EquipmentController:edit' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Controller\\EquipmentController:filterByCategory' => ['privates', '.service_locator.7P87fGM', 'get_ServiceLocator_7P87fGMService', true],
            'App\\Controller\\EquipmentController:filterByUser' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\EquipmentController:show' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Controller\\EquipmentController:unAssign' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Controller\\MoviesController:edit' => ['privates', '.service_locator.I4k6Jea', 'get_ServiceLocator_I4k6JeaService', true],
            'App\\Controller\\MoviesController:show' => ['privates', '.service_locator.I4k6Jea', 'get_ServiceLocator_I4k6JeaService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\UserController:getUserEquipment' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Service\\EquipmentService:assignEquipment' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Service\\EquipmentService:editEquipment' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'App\\Service\\EquipmentService:getEquipmentOfUserPaginate' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Service\\EquipmentService:unAssignEquipment' => ['privates', '.service_locator.vRM4WuB', 'get_ServiceLocator_VRM4WuBService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\EquipmentController::assign' => '?',
            'App\\Controller\\EquipmentController::edit' => '?',
            'App\\Controller\\EquipmentController::filterByCategory' => '?',
            'App\\Controller\\EquipmentController::filterByUser' => '?',
            'App\\Controller\\EquipmentController::show' => '?',
            'App\\Controller\\EquipmentController::unAssign' => '?',
            'App\\Controller\\MoviesController::edit' => '?',
            'App\\Controller\\MoviesController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::getUserEquipment' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'App\\Service\\EquipmentService::assignEquipment' => '?',
            'App\\Service\\EquipmentService::editEquipment' => '?',
            'App\\Service\\EquipmentService::getEquipmentOfUserPaginate' => '?',
            'App\\Service\\EquipmentService::unAssignEquipment' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\EquipmentController:assign' => '?',
            'App\\Controller\\EquipmentController:edit' => '?',
            'App\\Controller\\EquipmentController:filterByCategory' => '?',
            'App\\Controller\\EquipmentController:filterByUser' => '?',
            'App\\Controller\\EquipmentController:show' => '?',
            'App\\Controller\\EquipmentController:unAssign' => '?',
            'App\\Controller\\MoviesController:edit' => '?',
            'App\\Controller\\MoviesController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:getUserEquipment' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'App\\Service\\EquipmentService:assignEquipment' => '?',
            'App\\Service\\EquipmentService:editEquipment' => '?',
            'App\\Service\\EquipmentService:getEquipmentOfUserPaginate' => '?',
            'App\\Service\\EquipmentService:unAssignEquipment' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
