<?php

namespace ContainerTgNRuMC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1eTIucEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1eTIucE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1eTIucE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'equipment' => ['privates', '.errored..service_locator.1eTIucE.App\\Entity\\Equipment', NULL, 'Cannot autowire service ".service_locator.1eTIucE": it references class "App\\Entity\\Equipment" but no such service exists.'],
            'equipmentRepository' => ['services', 'App\\Repository\\EquipmentRepository', 'getEquipmentRepositoryService', true],
        ], [
            'equipment' => 'App\\Entity\\Equipment',
            'equipmentRepository' => 'App\\Repository\\EquipmentRepository',
        ]);
    }
}
