<?php

namespace Container7AuxcRI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I4k6JeaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I4k6Jea' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I4k6Jea'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movie' => ['privates', '.errored..service_locator.I4k6Jea.App\\Entity\\Movie', NULL, 'Cannot autowire service ".service_locator.I4k6Jea": it references class "App\\Entity\\Movie" but no such service exists.'],
        ], [
            'movie' => 'App\\Entity\\Movie',
        ]);
    }
}
