<?php

namespace ContainerLqS9RPK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7884i71Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7884i71' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7884i71'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'equipmentRepository' => ['services', 'App\\Repository\\EquipmentRepository', 'getEquipmentRepositoryService', true],
        ], [
            'equipmentRepository' => 'App\\Repository\\EquipmentRepository',
        ]);
    }
}
