<?php

namespace ContainerPl0nAjt;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PykiXDpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PykiXDp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PykiXDp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'user' => ['privates', '.errored..service_locator.PykiXDp.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.PykiXDp": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'paginator' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
