<?php

namespace ContainerXx9sWsk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\CategoryService' shared autowired service.
     *
     * @return \App\Service\CategoryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/CategoryService.php';

        return $container->services['App\\Service\\CategoryService'] = new \App\Service\CategoryService(($container->services['App\\Repository\\CategoryRepository'] ?? $container->load('getCategoryRepositoryService')));
    }
}
