<?php

namespace ContainerXx9sWsk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEquipmentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EquipmentController' shared autowired service.
     *
     * @return \App\Controller\EquipmentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TokenAuthenticatedControllerr.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EquipmentController.php';

        $container->services['App\\Controller\\EquipmentController'] = $instance = new \App\Controller\EquipmentController(($container->services['App\\Service\\EquipmentService'] ?? $container->load('getEquipmentServiceService')), ($container->services['App\\Service\\CategoryService'] ?? $container->load('getCategoryServiceService')), ($container->services['App\\Service\\UserService'] ?? $container->load('getUserServiceService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\EquipmentController', $container));

        return $instance;
    }
}
