<?php

<<<<<<< HEAD:var/cache/dev/ContainerFFfIZfl/getCache_SystemService.php
namespace ContainerFFfIZfl;

=======
namespace ContainerY1G2mUW;
>>>>>>> 9b03bdf0df8650d60f8b2bd0d2214076809a92cf:var/cache/dev/ContainerY1G2mUW/getCache_SystemService.php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_SystemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cache.system' shared service.
     *
     * @return \Symfony\Component\Cache\Adapter\AdapterInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['cache.system'] = \Symfony\Component\Cache\Adapter\AbstractAdapter::createSystemCache('ss1EU5RoCW', 0, $container->getParameter('container.build_id'), ($container->targetDir.''.'/pools/system'), ($container->privates['logger'] ?? ($container->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger())));
    }
}
