<?php

namespace ContainerInZ92xh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEquipmentServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\EquipmentService' shared autowired service.
     *
     * @return \App\Service\EquipmentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'DataValidate.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'EquipmentService.php';

        $container->services['App\\Service\\EquipmentService'] = $instance = new \App\Service\EquipmentService(($container->services['App\\Repository\\EquipmentRepository'] ?? $container->load('getEquipmentRepositoryService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['App\\Service\\CategoryService'] ?? $container->load('getCategoryServiceService')), ($container->privates['validator'] ?? $container->load('getValidatorService')), ($container->services['App\\Repository\\AssignRepository'] ?? $container->load('getAssignRepositoryService')), ($container->services['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Service\\EquipmentService', $container));

        return $instance;
    }
}
