<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFFfIZfl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFFfIZfl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFFfIZfl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFFfIZfl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFFfIZfl\App_KernelDevDebugContainer([
    'container.build_hash' => 'FFfIZfl',
    'container.build_id' => '33d6e42d',
    'container.build_time' => 1656313690,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFFfIZfl');
