<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHFUAxog\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHFUAxog/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHFUAxog.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHFUAxog\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHFUAxog\App_KernelDevDebugContainer([
    'container.build_hash' => 'HFUAxog',
    'container.build_id' => '4db60327',
    'container.build_time' => 1657063476,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHFUAxog');
