<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNF9gM0v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNF9gM0v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNF9gM0v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNF9gM0v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNF9gM0v\App_KernelDevDebugContainer([
    'container.build_hash' => 'NF9gM0v',
    'container.build_id' => '65002c50',
    'container.build_time' => 1656561295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNF9gM0v');
