<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_equipment_index' => [[], ['_controller' => 'App\\Controller\\EquipmentController::index'], [], [['text', '/equipments/']], [], [], []],
    'app_equipment_filter_by_category' => [['category'], ['_controller' => 'App\\Controller\\EquipmentController::filterByCategory'], [], [['variable', '/', '[^/]++', 'category', true], ['text', '/equipments/category']], [], [], []],
    'app_equipment_new' => [[], ['_controller' => 'App\\Controller\\EquipmentController::new'], [], [['text', '/equipments/new']], [], [], []],
    'app_equipment_show' => [['equipment'], ['_controller' => 'App\\Controller\\EquipmentController::show'], [], [['variable', '/', '[^/]++', 'equipment', true], ['text', '/equipments']], [], [], []],
    'app_equipment_edit' => [['equipment'], ['_controller' => 'App\\Controller\\EquipmentController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'equipment', true], ['text', '/equipments/api']], [], [], []],
    'app_equipment_assign' => [['equipment'], ['_controller' => 'App\\Controller\\EquipmentController::assign'], [], [['text', '/assign'], ['variable', '/', '[^/]++', 'equipment', true], ['text', '/equipments/api']], [], [], []],
    'app_equipment_unassign' => [['equipment'], ['_controller' => 'App\\Controller\\EquipmentController::unAssign'], [], [['text', '/unassign'], ['variable', '/', '[^/]++', 'equipment', true], ['text', '/equipments/api']], [], [], []],
    'app_equipment_delete' => [['id'], ['_controller' => 'App\\Controller\\EquipmentController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/equipments']], [], [], []],
    'app_equipment_filterbyuser' => [['id'], ['_controller' => 'App\\Controller\\EquipmentController::filterByUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/equipments/user']], [], [], []],
    'app_movie' => [[], ['_controller' => 'App\\Controller\\MovieController::index'], [], [['text', '/movie']], [], [], []],
    'movies' => [[], ['_controller' => 'App\\Controller\\MoviesController::index'], [], [['text', '/movies']], [], [], []],
    'app_movies_create' => [[], ['_controller' => 'App\\Controller\\MoviesController::create'], [], [['text', '/movies/create']], [], [], []],
    'editMovie' => [['movie'], ['_controller' => 'App\\Controller\\MoviesController::edit'], [], [['variable', '/', '[^/]++', 'movie', true], ['text', '/movies/edit']], [], [], []],
    'app_movies_show' => [['movie'], ['_controller' => 'App\\Controller\\MoviesController::show'], [], [['variable', '/', '[^/]++', 'movie', true], ['text', '/movies']], [], [], []],
    'old' => [[], ['_controller' => 'App\\Controller\\MoviesController::show'], [], [['text', '/show']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_user_index' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/']], [], [], []],
    'app_user_new' => [[], ['_controller' => 'App\\Controller\\UserController::new'], [], [['text', '/user/new']], [], [], []],
    'app_user_show' => [['id'], ['_controller' => 'App\\Controller\\UserController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'app_user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'app_user_delete' => [['id'], ['_controller' => 'App\\Controller\\UserController::getUserEquipment'], [], [['text', '/equipment'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user']], [], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\VinylController::homepage'], [], [['text', '/']], [], [], []],
    'app_vinyl_browse' => [['name'], ['name' => null, '_controller' => 'App\\Controller\\VinylController::Browse'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/browse']], [], [], []],
];
