<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_movie' => [[], ['_controller' => 'App\\Controller\\MovieController::index'], [], [['text', '/movie']], [], [], []],
    'movies' => [[], ['_controller' => 'App\\Controller\\MoviesController::index'], [], [['text', '/movies']], [], [], []],
    'app_movies_create' => [[], ['_controller' => 'App\\Controller\\MoviesController::create'], [], [['text', '/movies/create']], [], [], []],
    'app_movies_show' => [['movie'], ['_controller' => 'App\\Controller\\MoviesController::show'], [], [['variable', '/', '[^/]++', 'movie', true], ['text', '/movies']], [], [], []],
    'old' => [[], ['_controller' => 'App\\Controller\\MoviesController::show'], [], [['text', '/show']], [], [], []],
    'app_vinyl_homepage' => [[], ['_controller' => 'App\\Controller\\VinylController::homepage'], [], [['text', '/']], [], [], []],
    'app_vinyl_browse' => [['name'], ['name' => null, '_controller' => 'App\\Controller\\VinylController::Browse'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/browse']], [], [], []],
];
